version: "3.7"
services:
  ## php-fpm
  php:
    container_name: php
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
#    image: yfix/php:7.4
    volumes:
#      - ../ecommerce:/ecommerce
      - ../xbot-blog:/xbot-blog
      - ../xbot-php:/xbot-php
    networks:
      - app-network
    working_dir: ${WORKING_DIR}
    environment:
      PHP_IDE_CONFIG: serverName=${PROJECT_NAME}

  ## nginx
  nginx:
    container_name: web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../xbot-blog:/xbot-blog
      - ../xbot-php:/xbot-php
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    working_dir: ${WORKING_DIR}

  db:
    image: postgres:12.3
    volumes:
      - db_backup:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: db
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  ## redis
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ./data/redis:/data
    ports:
      - "8001:6379"
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network
  # https://stackoverflow.com/questions/53089486/unable-to-connect-to-kafka-run-in-container-from-spring-boot-app-run-outside-con
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper
    networks:
      - app-network

volumes:
  db_backup:

#Docker Networks
networks:
  app-network:
    driver: bridge
