version: "3.7"
services:
  ## php-fpm
  php:
    build:
      context: ./.docker/localdev/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ../ecommerce:/ecommerce
    depends_on:
      - db
      - redis
    working_dir: /ecommerce
    environment:
      PHP_IDE_CONFIG: serverName=${PROJECT_NAME}

  ## nginx
  nginx:
    container_name: web
    build:
      context: ./.docker/localdev/nginx
      dockerfile: Dockerfile
    volumes:
      - ../ecommerce:/ecommerce
#      - type: bind
#        source: ./swagger
#        target: /swagger
      - type: bind
        source: ./.docker/localdev/nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
    depends_on:
      - php
      - node
    ports:
      - "8000:80"
      - "443:443"
    working_dir: /ecommerce

  db:
    image: postgres:12.3
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: atm
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: ecommerce

  ## redis
  redis:
    container_name: redis
    image: redis:alpine

  ## node
  node:
    container_name: node
    image: node
    volumes:
      - type: bind
        source: ../ecommerce
        target: /ecommerce
      - type: bind
        source: .docker/localdev/node/scripts
        target: /scripts
        read_only: true
    depends_on:
      - db
    working_dir: /ecommerce
    entrypoint: /scripts/bootstrap.sh
